-- Migration 0028: seed de receitas Sul (gerado por scripts/generate-recipes-seed.mjs)
-- 22 receitas curadas para region='sul'. UPSERT por slug.

delete from public.recipes where region = 'sul';

insert into public.recipes (slug, title, icon, category, time_label, description, region, state, data) values
  ('peixe_grelhado_sul', 'Peixe Grelhado Simples', '🐟', 'Jantar · Fit', '15 min', 'Filé de peixe grelhado na chapa com azeite e limão.', 'sul', 'RS', '{"ings":[{"n":"Filé de peixe firme","a":"300 g"},{"n":"Limão, alho, azeite","a":"a gosto"},{"n":"Sal, pimenta, salsa","a":"a gosto"}],"steps":["Tempere o peixe com limão, alho, sal e pimenta.","Seque bem antes de grelhar.","Aqueça frigideira com fio de azeite.","Grelhe 3 min cada lado.","Finalize com salsa fresca."],"tip":"Secar o peixe é 80% do ponto crocante — não pule."}'::jsonb),
  ('arroz_carreteiro', 'Arroz Carreteiro', '🍚', 'Almoço · Gaúcho', '45 min', 'Arroz misturado com charque desfiado — prato do carreteiro gaúcho.', 'sul', 'RS', '{"ings":[{"n":"Charque dessalgado desfiado","a":"200 g"},{"n":"Arroz branco cru","a":"1 xícara"},{"n":"Cebola, alho, pimentão, tomate","a":"a gosto"},{"n":"Cheiro-verde, pimenta-calabresa","a":"a gosto"}],"steps":["Dessalgue o charque; cozinhe em pressão por 30 min; desfie.","Refogue cebola e alho em panela larga.","Doure o charque desfiado por 5 min.","Acrescente pimentão e tomate picados.","Junte o arroz lavado e mexa bem.","Cubra com 2 xícaras de água fervente; cozinhe por 15 min.","Finalize com cheiro-verde."],"tip":"Tradicionalmente feito em panela de ferro no fogão a lenha — a crostinha do fundo é o melhor."}'::jsonb),
  ('patinho_ensopado_polenta', 'Patinho Ensopado Rápido c/ Polenta Mole', '🥩', 'Almoço · Paranaense light', '20 min', 'Versão prática do ensopado paranaense: patinho em cubos refogado rápido, servido com polenta mole leve.', 'sul', 'PR', '{"ings":[{"n":"Patinho em cubos pequenos","a":"150 g"},{"n":"Molho de tomate caseiro","a":"1/2 xícara"},{"n":"Cebola, alho, louro, cominho","a":"a gosto"},{"n":"Fubá","a":"1/2 xícara"},{"n":"Caldo de legumes leve","a":"2 xícaras"},{"n":"Salada verde (acompanhamento)","a":"à vontade"}],"steps":["Tempere o patinho em cubos com alho, sal, cominho e louro; 10 min.","Doure em panela quente com fio de azeite por 5 min.","Acrescente cebola, molho de tomate e 1/2 xícara de água; cozinhe 8 min.","Em paralelo, ferva o caldo; despeje fubá em chuva mexendo.","Cozinhe a polenta 12 min em fogo baixo até firmar levemente.","Sirva o patinho ensopado sobre a polenta + salada verde."],"tip":"Patinho em cubos pequenos cozinha em 8-10 min — não precisa pressão nem 8h de panela de barro."}'::jsonb),
  ('camarao_milanesa', 'Camarão à Milanesa', '🦐', 'Almoço · Litorâneo', '25 min', 'Camarão empanado e frito com farinha de rosca — clássico do litoral sul.', 'sul', 'SC', '{"ings":[{"n":"Camarão grande limpo","a":"300 g"},{"n":"Farinha de trigo","a":"1/2 xícara"},{"n":"Ovos batidos","a":"2 unidades"},{"n":"Farinha de rosca","a":"1 xícara"},{"n":"Limão, alho, sal, pimenta","a":"a gosto"}],"steps":["Tempere o camarão com limão, alho, sal e pimenta; 15 min.","Passe cada camarão na farinha, no ovo, na farinha de rosca.","Aqueça óleo (fritadeira ou panela) a 180 °C.","Frite por 3 min até dourar.","Escorra em papel-toalha.","Sirva com limão e arroz branco."],"tip":"Camarão frito demais fica borrachudo — 3 min no óleo bem quente é o limite."}'::jsonb),
  ('canja_galinha_sul', 'Canja de Galinha', '🍲', 'Jantar · Reconfortante', '45 min', 'Caldo simples de galinha com arroz e legumes — universal.', 'sul', 'RS', '{"ings":[{"n":"Peito de galinha com osso","a":"300 g"},{"n":"Arroz cru","a":"1/3 xícara"},{"n":"Cenoura, batata, chuchu em cubos","a":"2 xícaras"},{"n":"Cebola, alho, louro, salsa","a":"a gosto"}],"steps":["Cozinhe a galinha por 30 min em 1,5 l de água com louro.","Retire, desfie e devolva o caldo ao fogo.","Adicione arroz; cozinhe 8 min.","Junte os legumes; cozinhe mais 10 min.","Devolva a galinha; finalize com salsa."],"tip":"No Sul costumam adicionar cenoura ralada fina — derrete no caldo e dá cor."}'::jsonb),
  ('churrasco_misto', 'Churrasco Misto', '🔥', 'Almoço · Gaúcho', '1h30', 'Combinação de picanha e fraldinha assadas na brasa — o básico do churrasco gaúcho.', 'sul', 'RS', '{"ings":[{"n":"Picanha em peça","a":"400 g"},{"n":"Fraldinha em peça","a":"300 g"},{"n":"Sal grosso","a":"3 col sopa"}],"steps":["Deixe as carnes em temperatura ambiente por 30 min.","Espete a picanha em peça inteira (gordura para fora).","Espete a fraldinha pela lateral longa.","Prepare brasa bem viva.","Salgue as carnes só na hora de ir pra grelha.","Picanha: 20 min cada lado em brasa média; fraldinha: 15 min.","Descanse as carnes 5 min antes de fatiar."],"tip":"Sal grosso aplicado na hora — se colocar antes, ''cozinha'' a superfície e resseca."}'::jsonb),
  ('costela_brasa', 'Costela Assada na Brasa', '🥩', 'Almoço · Gaúcho', '5h', 'Costela bovina assada lentamente na brasa a mais de 1 metro de distância — ponto de honra gaúcho.', 'sul', 'RS', '{"ings":[{"n":"Costela bovina em ripa","a":"1 kg"},{"n":"Sal grosso","a":"3 col sopa"}],"steps":["Espete a costela inteira em vara de churrasco.","Esfregue sal grosso só no lado da carne (não na gordura).","Coloque em brasa baixa a distância de 80cm a 1m.","Asse por 5h virando a cada 1h.","Nos últimos 30 min, aproxime para dourar a gordura.","Sirva em lascas soltas."],"tip":"Fogo de chão leva 8h; na churrasqueira alta, 5h. Na horizontal sem altura ajustável, use forno a 140 °C por 4h."}'::jsonb),
  ('frango_arroz_pinhao_repolho', 'Frango c/ Arroz, Pinhão e Repolho Refogado', '🐔', 'Almoço · Fit sazonal', '22 min', 'Frango em cubos grelhado com arroz, poucos pinhões como acento regional e repolho refogado leve — versão prática do entrevero.', 'sul', 'SC', '{"ings":[{"n":"Peito de frango em cubos","a":"140 g"},{"n":"Arroz branco cozido","a":"1 xícara"},{"n":"Pinhão cozido","a":"15 g"},{"n":"Repolho roxo ou verde em tiras","a":"2 xícaras"},{"n":"Alho, cebola, pimenta, azeite","a":"a gosto"}],"steps":["Tempere o frango com alho e sal; grelhe em fio de azeite por 6 min.","Em outra frigideira, refogue cebola e alho.","Acrescente o repolho em tiras finas; refogue 3-4 min até murchar levemente.","Finalize o repolho com pimenta e sal.","Monte o prato: arroz, frango grelhado por cima, pinhão salpicado, repolho ao lado."],"tip":"Pinhão aqui é acento regional (15g) — não base. O repolho al dente mantém crocância e vitaminas."}'::jsonb),
  ('frango_assado_batata_sul', 'Frango Assado com Batata-Doce', '🐔', 'Jantar · Fit', '50 min', 'Filés de frango assados com batata-doce em cubos — balanceado.', 'sul', 'RS', '{"ings":[{"n":"Peito de frango em filés","a":"400 g"},{"n":"Batata-doce em cubos","a":"400 g"},{"n":"Alho, alecrim, páprica","a":"a gosto"},{"n":"Azeite, sal, pimenta, limão","a":"a gosto"}],"steps":["Tempere o frango com limão, alho, páprica; 20 min.","Espalhe batata com azeite, sal e alecrim numa assadeira.","Disponha os filés por cima.","Cubra com papel alumínio; asse a 200 °C por 25 min.","Retire o alumínio; doure por mais 15 min.","Sirva com salada."],"tip":"Corte a batata em cubos iguais (~3cm) para assar por igual."}'::jsonb),
  ('galeto_primo_canto', 'Galeto al Primo Canto', '🐔', 'Almoço · Italiano-gaúcho', '1h', 'Frango jovem temperado com ervas e assado na brasa — tradição italiana de Caxias/Garibaldi.', 'sul', 'RS', '{"ings":[{"n":"Frango jovem (galeto) aberto","a":"1 unidade (~800g)"},{"n":"Alho, alecrim, manjerona, sálvia","a":"a gosto"},{"n":"Vinho branco, azeite, sal","a":"a gosto"},{"n":"Polenta frita (acompanhamento)","a":"4 fatias"}],"steps":["Abra o galeto (passaredo ou peça ao açougueiro).","Marinhe com alho, ervas, vinho, azeite e sal por 3h.","Asse em espeto ou grelha com brasa média por 40 min.","Pincele a marinada durante o assado.","Fatie a polenta firme e frite em óleo quente.","Sirva galeto com polenta frita ao lado."],"tip":"''Al primo canto'' significa ''no primeiro canto'' — frango jovem, de até 40 dias, bem macio."}'::jsonb),
  ('kassler', 'Kassler com Purê', '🥓', 'Almoço · Catarinense-alemão', '30 min', 'Carne de porco defumada (kassler) grelhada servida com purê de batata.', 'sul', 'SC', '{"ings":[{"n":"Kassler em fatias","a":"300 g"},{"n":"Batata cozida","a":"500 g"},{"n":"Leite, manteiga, noz-moscada","a":"a gosto"},{"n":"Chucrute (acompanhamento)","a":"1 xícara"}],"steps":["Grelhe as fatias de kassler 2 min cada lado (já vem cozido).","Cozinhe batata; amasse com leite, manteiga e noz-moscada.","Aqueça o chucrute em panela separada por 5 min.","Monte o prato: kassler, purê, chucrute.","Opcional: mostarda ao lado."],"tip":"Kassler já é defumado/cozido — só precisa grelhar pra dourar, não cozinhar."}'::jsonb),
  ('patinho_batata_doce_salada', 'Patinho Grelhado c/ Batata-Doce', '🥩', 'Almoço · Fit', '22 min', 'Filé de patinho grelhado com batata-doce assada e salada de folhas — prato gaúcho leve, sem enrolado nem gordura extra.', 'sul', 'RS', '{"ings":[{"n":"Filé de patinho (peça inteira)","a":"150 g"},{"n":"Batata-doce em cubos","a":"100 g"},{"n":"Folhas verdes (alface, rúcula)","a":"à vontade"},{"n":"Tomate, cenoura ralada","a":"a gosto"},{"n":"Alho, sal, pimenta, azeite, limão","a":"a gosto"}],"steps":["Corte a batata em cubos; tempere com azeite, sal e alecrim.","Leve ao forno a 200 °C por 20 min até dourar.","Tempere o patinho com alho, sal e pimenta; 10 min.","Grelhe em frigideira quente 3-4 min cada lado (médio).","Descanse 2 min e fatie.","Monte: carne, batata-doce, salada de folhas c/ tomate e cenoura.","Finalize a salada com limão e fio de azeite."],"tip":"Grelhar por pouco tempo deixa o patinho no ponto — passou do médio, resseca."}'::jsonb),
  ('omelete_queijo_colonial', 'Omelete com Queijo Colonial', '🍳', 'Jantar · Rápido', '10 min', 'Omelete simples com queijo colonial (semi-duro) em cubos.', 'sul', 'SC', '{"ings":[{"n":"Ovos","a":"3 unidades"},{"n":"Queijo colonial em cubos","a":"80 g"},{"n":"Cebolinha, manteiga, sal, pimenta","a":"a gosto"}],"steps":["Bata os ovos com sal, pimenta e cebolinha.","Aqueça manteiga na frigideira.","Despeje os ovos; quando firmar, adicione queijo colonial.","Dobre ao meio; cozinhe 1 min.","Sirva com salada."],"tip":"Queijo colonial é mais firme que minas — derrete mais lentamente e segura textura."}'::jsonb),
  ('polenta_fortaia', 'Polenta com Fortaia', '🌽', 'Jantar · Ítalo-gaúcho', '35 min', 'Polenta mole acompanhada de fortaia (omelete com queijo) — prato ítalo-gaúcho.', 'sul', 'RS', '{"ings":[{"n":"Fubá de milho","a":"1 xícara"},{"n":"Caldo de legumes","a":"4 xícaras"},{"n":"Ovos","a":"3 unidades"},{"n":"Queijo colonial ralado","a":"100 g"},{"n":"Manteiga, sal","a":"a gosto"}],"steps":["Ferva o caldo; adicione fubá em chuva mexendo.","Cozinhe 20 min em fogo baixo até virar polenta cremosa.","Para a fortaia: bata ovos com sal e queijo ralado.","Derreta manteiga em frigideira; despeje a mistura.","Cozinhe 3 min; vire e mais 2 min.","Sirva a polenta com a fortaia em fatias por cima."],"tip":"Fortaia é quase omelete, mas mais espessa e dourada — quase uma panqueca salgada."}'::jsonb),
  ('polenta_frango', 'Polenta com Frango Ensopado', '🐔', 'Almoço · Ítalo-gaúcho', '45 min', 'Polenta mole servida com frango ensopado em molho de tomate.', 'sul', 'RS', '{"ings":[{"n":"Peito ou coxa desossada em pedaços","a":"400 g"},{"n":"Molho de tomate caseiro","a":"1,5 xícaras"},{"n":"Fubá","a":"1 xícara"},{"n":"Caldo, manteiga, queijo ralado","a":"a gosto"},{"n":"Cebola, alho, ervas","a":"a gosto"}],"steps":["Tempere o frango; doure em panela.","Acrescente cebola, alho e molho de tomate.","Cubra com água e cozinhe 25 min.","Prepare a polenta (fubá + caldo, mexer 20 min).","Finalize a polenta com manteiga e queijo ralado.","Sirva a polenta com o frango e molho por cima."],"tip":"Use coxa desossada — fica mais suculenta que peito em molhos longos."}'::jsonb),
  ('arroz_frango_alecrim_pinhao_light', 'Arroz Integral c/ Frango ao Alecrim e Pinhão', '🐔', 'Almoço · Fit sazonal', '25 min', 'Arroz integral com peito de frango grelhado ao alecrim e acento de pinhão cozido — sabor serrano sem a cremosidade do risoto.', 'sul', 'SC', '{"ings":[{"n":"Arroz integral cozido","a":"1 xícara"},{"n":"Peito de frango em cubos","a":"140 g"},{"n":"Pinhão cozido descascado","a":"15 g"},{"n":"Alecrim fresco, alho, azeite","a":"a gosto"},{"n":"Couve refogada (acompanhamento)","a":"1 xícara"}],"steps":["Tempere o frango em cubos com alho, sal e alecrim; 10 min.","Grelhe o frango em fio de azeite por 5-6 min até dourar.","Aqueça o arroz integral em frigideira larga.","Incorpore o pinhão cozido e o frango grelhado.","Misture bem e finalize com alecrim fresco.","Sirva com couve refogada ao lado."],"tip":"Pinhão aqui é tempero, não base — 15g já entrega o sabor sem inflar a gordura como um risoto."}'::jsonb),
  ('arroz_frango_alecrim_jantar', 'Arroz Integral c/ Frango Desfiado ao Alecrim', '🍲', 'Jantar · Fit', '18 min', 'Arroz integral com frango desfiado ao alecrim e salada de folhas — versão leve e rápida para o jantar, sem cremosidade de risoto.', 'sul', 'PR', '{"ings":[{"n":"Arroz integral cozido","a":"3/4 xícara"},{"n":"Peito de frango desfiado","a":"120 g"},{"n":"Alecrim fresco, salsa, alho","a":"a gosto"},{"n":"Azeite, sal, pimenta","a":"a gosto"},{"n":"Folhas verdes c/ tomate","a":"à vontade"}],"steps":["Tempere o frango desfiado com alho, alecrim e sal.","Aqueça fio de azeite; refogue o frango por 3 min.","Adicione o arroz integral já cozido; misture e aqueça.","Finalize com salsa fresca picada.","Sirva com salada de folhas e tomate."],"tip":"Use frango cozido do almoço — vira jantar em 10 min sem ligar forno."}'::jsonb),
  ('sequencia_catarinense_light', 'Sequência Catarinense Light', '🦐', 'Jantar · Fit', '30 min', 'Mini-sequência catarinense: peixe grelhado + camarão (sem as frituras).', 'sul', 'SC', '{"ings":[{"n":"Filé de peixe branco","a":"200 g"},{"n":"Camarão limpo","a":"160 g"},{"n":"Limão, alho, manteiga","a":"a gosto"},{"n":"Arroz branco cozido","a":"1 xícara"},{"n":"Salada verde","a":"à vontade"}],"steps":["Tempere peixe e camarão com limão, alho, sal; 15 min.","Grelhe o peixe 3 min cada lado em fio de manteiga.","Salteie o camarão na mesma frigideira por 3 min.","Monte o prato: peixe, camarão, arroz, salada.","Sirva com fatia extra de limão."],"tip":"Sequência tradicional tem 6+ pratos (inclui ostras, camarão frito, empadão). Esta é a versão minimalista fit."}'::jsonb),
  ('sopa_agnolini', 'Sopa de Agnolini', '🥟', 'Jantar · Ítalo-gaúcho', '40 min', 'Caldo de galinha com agnolini (massa recheada em formato de anel).', 'sul', 'RS', '{"ings":[{"n":"Agnolini (pronto ou caseiro)","a":"300 g"},{"n":"Caldo de galinha caseiro","a":"1,5 l"},{"n":"Parmesão ralado","a":"a gosto"},{"n":"Salsa, cebolinha","a":"a gosto"}],"steps":["Ferva o caldo de galinha bem temperado.","Cozinhe os agnolini direto no caldo por 5-8 min (conforme embalagem).","Sirva quente com parmesão ralado por cima.","Finalize com salsa fresca."],"tip":"Agnolini fresco cozinha em 3 min, seco em 8-10 min — não deixe passar do ponto."}'::jsonb),
  ('sopa_capeletti', 'Sopa de Capeletti', '🍲', 'Jantar · Ítalo-gaúcho', '40 min', 'Caldo claro com massinha recheada capeletti — prato de Natal italiano no Sul.', 'sul', 'RS', '{"ings":[{"n":"Capeletti (recheado)","a":"300 g"},{"n":"Caldo de carne ou galinha","a":"1,5 l"},{"n":"Parmesão ralado","a":"a gosto"},{"n":"Salsa","a":"a gosto"}],"steps":["Ferva o caldo.","Cozinhe o capeletti no caldo por 5-8 min.","Sirva quente com parmesão.","Finalize com salsa."],"tip":"Capeletti quer dizer ''chapeuzinho'' em italiano — forma diferente do agnolini (anel)."}'::jsonb),
  ('sopa_feijao_charque_sul', 'Sopa de Feijão Preto com Charque', '🥣', 'Jantar · Gaúcho', '40 min', 'Caldo encorpado de feijão preto com charque desfiado.', 'sul', 'RS', '{"ings":[{"n":"Feijão preto cozido com caldo","a":"2 xícaras"},{"n":"Charque dessalgado desfiado","a":"150 g"},{"n":"Cebola, alho, louro","a":"a gosto"},{"n":"Cheiro-verde, pimenta-calabresa","a":"a gosto"}],"steps":["Dessalgue e cozinhe o charque; desfie.","Bata metade do feijão com caldo.","Refogue cebola, alho em panela funda.","Junte charque, feijão batido e feijão inteiro + 500 ml água.","Cozinhe por 15 min em fogo baixo.","Finalize com cheiro-verde."],"tip":"Feijão preto com caldo grosso é mais gaúcho que o carioca — escolha bem o feijão."}'::jsonb),
  ('sopa_feijao_carne_magra', 'Sopa de Feijão Preto c/ Patinho Desfiado', '🥣', 'Jantar · Reconfortante', '25 min', 'Sopa encorpada de feijão preto com patinho desfiado e legumes — alternativa leve à sopa de pinhão no inverno.', 'sul', 'RS', '{"ings":[{"n":"Feijão preto cozido com caldo","a":"1,5 xícaras"},{"n":"Patinho cozido e desfiado","a":"60 g"},{"n":"Cenoura, batata em cubos","a":"1 xícara"},{"n":"Cebola, alho, louro","a":"a gosto"},{"n":"Cheiro-verde, pimenta","a":"a gosto"},{"n":"Torrada integral (acompanhamento)","a":"1 fatia"}],"steps":["Bata 1/3 do feijão com o caldo no liquidificador (dá corpo).","Refogue cebola e alho em fio de azeite.","Acrescente feijão batido + feijão inteiro + cenoura e batata; cozinhe 12 min.","Junte o patinho desfiado e aqueça 3 min.","Finalize com cheiro-verde.","Sirva com torrada integral."],"tip":"Usar uma parte batida dá textura cremosa sem creme de leite — e 60g de patinho desfiado entrega proteína sem pesar."}'::jsonb)
on conflict (slug) do update set
  title = excluded.title,
  icon = excluded.icon,
  category = excluded.category,
  time_label = excluded.time_label,
  description = excluded.description,
  region = excluded.region,
  state = excluded.state,
  data = excluded.data;
